# Generated by Django 6.0.3 on 2026-03-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemandaETL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data_recebimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Desenvolvimento"),
                            ("T", "Homologação"),
                            ("P", "Produção"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                (
                    "complexidade",
                    models.CharField(
                        choices=[("B", "Baixa"), ("M", "Média"), ("A", "Alta")],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "folder_repositorio",
                    models.CharField(
                        help_text="Pasta no Repository Manager", max_length=100
                    ),
                ),
                (
                    "workflow_mapping",
                    models.CharField(max_length=255, verbose_name="Workflow/Mapping"),
                ),
                (
                    "origem_destino",
                    models.CharField(
                        help_text="Ex: Oracle CRM -> Teradata DW", max_length=255
                    ),
                ),
                (
                    "descricao_solucao",
                    models.TextField(verbose_name="O que foi desenvolvido"),
                ),
                (
                    "script_sql_shell",
                    models.TextField(
                        blank=True,
                        verbose_name="Queries SQL ou Scripts Shell utilizados",
                    ),
                ),
                (
                    "arquivo_tecnico",
                    models.FileField(
                        upload_to="documentos_pc/",
                        verbose_name="Anexo (Proposta Técnica)",
                    ),
                ),
            ],
        ),
    ]
