# Generated by Django 6.0.3 on 2026-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandaetl",
            name="data_implementacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Implementação"
            ),
        ),
        migrations.AddField(
            model_name="demandaetl",
            name="id_demanda",
            field=models.CharField(
                default="", max_length=50, verbose_name="ID da Demanda/Ticket"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="demandaetl",
            name="lider_tecnico",
            field=models.CharField(
                default="", max_length=100, verbose_name="TL (Líder Técnico)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="demandaetl",
            name="folder_repositorio",
            field=models.CharField(
                max_length=100, verbose_name="Pasta no Repository Manager"
            ),
        ),
    ]
