# Generated by Django 6.0.3 on 2026-03-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "demandas",
            "0002_demandaetl_data_implementacao_demandaetl_id_demanda_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandaetl",
            name="script_sql_shell",
            field=models.TextField(
                blank=True, verbose_name="Queries SQL ou Scripts Shell"
            ),
        ),
        migrations.AlterField(
            model_name="demandaetl",
            name="titulo",
            field=models.CharField(max_length=400),
        ),
    ]
