# Generated by Django 6.0.3 on 2026-03-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0003_alter_demandaetl_script_sql_shell_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandaetl",
            name="link_jira",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link do Card Jira"
            ),
        ),
    ]
