# Generated by Django 6.0.3 on 2026-03-12 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0004_demandaetl_link_jira"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandaetl",
            name="data_implementacao",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Data Limite de Implantação",
            ),
            preserve_default=False,
        ),
    ]
