# Generated by Django 6.0.3 on 2026-03-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0005_alter_demandaetl_data_implementacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandaetl",
            name="data_implementacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Limite de Implantação"
            ),
        ),
        migrations.AlterField(
            model_name="demandaetl",
            name="data_recebimento",
            field=models.DateField(
                auto_now_add=True, verbose_name="Data de Recebimento"
            ),
        ),
    ]
